--- #YAML:1.0
name:                DBIx-Class-RandomStringColumns
version:             0.05
abstract:            Implicit random string columns
license:             ~
author:              
    - Kan Fushihara <kan __at__ mobilefactory.jp>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    String::Random:                0
    Test::More:                    0
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
